### ISSUE TITLE
Распределённые приложения <- Книга Масштабирование приложений. Атчисон Ли

### ISSUE THREAD

**Issue by kreghek** [sbzenenko/ASP.NET-MVC-Exam-70-486#1]
Могу предложить этот материал. К сожалению, конкретных страниц/разделов не укажу. Но по сути там вся книга о том, что рассказывается в Exam Refs 70-486 в разделе 1.2 Распределённые приложения.
https://www.ozon.ru/context/detail/id/144864240/

**Comment by sbenzenko** [comment]
Спасибо за предложение. Посмотрю
