### ISSUE TITLE
Раздел 1.2. Веб-фермы. Липкая сессия.

### ISSUE THREAD

**Issue by kreghek** [sbzenenko/ASP.NET-MVC-Exam-70-486#2]
В Exam Refs не совсем понятно напимано, что это.
Более подробно рассписано здесь https://stackoverflow.com/questions/10494431/sticky-and-non-sticky-sessions. Возможно, стоит всключить ссылку.

**Comment by sbenzenko** [comment]
Добавил, спасибо
