### ISSUE TITLE
1.1.5 Еще одна статья от майков, как выбирать между коркой и фреймворком

### ISSUE THREAD

**Issue by kreghek** [sbzenenko/ASP.NET-MVC-Exam-70-486#3]
https://docs.microsoft.com/en-us/dotnet/standard/choosing-core-framework-server

На мой взгляд она больше нацелена выбор между платформами

**Comment by sbenzenko** [comment]
Да, там вопрос про ASP. Но всё равно полезно будет. Добавил.

**Comment by kreghek** [comment]
> Да, там вопрос про ASP. Но всё равно полезно будет. Добавил.

Так и экзамен про ASP :)
